### ISSUE TITLE
Dollar sign as part of a template string is not escaped

### ISSUE THREAD

**Issue by alexjeffburke** [unexpectedjs/unexpected-snapshot#56]
I was using `unexpected-snapshot` as part of testing the output of my markdown generating tool `evaldown`. In one of the tests a chunk of code within a ``` markdown code block was output that contained a template string. Opening the test file in an editor afterwards showed a syntax error.

My understanding is that since the output itself wrapped in expect.unindent```...```, the dollar sign in a contained template string needs to be escaped. On adding a `\` before it, the syntax error went away and then "check" only version of test suite passed.

**Comment by papandreou** [comment]
Fixed in 1.0.1 🤗
